'use client';

import { useEffect, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { Suspense } from 'react';

const steps = ['Member information', 'Loan information', 'Financial information', 'Guarantor information', 'Document upload', 'Review and submit'];

function LoanApplicationForm() {
  const params = useSearchParams();
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [message, setMessage] = useState('');
  const [form, setForm] = useState({ type: params.get('type') || 'GENERAL', loanProductId: params.get('product') || '', amount: '', purpose: '', repaymentPeriod: '', repaymentFrequency: 'MONTHLY', guarantorName: '', guarantorPhone: '', guarantorAddress: '', guarantorRelationship: '', propertyType: '', propertyLocation: '', propertyValue: '', propertyDocuments: '', supportingDocuments: '', documents: '', commodityItems: '' });
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => {
    setMessage('Submitting application...');
    const response = await fetch('/api/loans', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, amount: Number(form.amount), repaymentPeriod: form.repaymentPeriod ? Number(form.repaymentPeriod) : undefined, propertyValue: form.propertyValue ? Number(form.propertyValue) : undefined }) });
    const data = await response.json();
    if (!response.ok) { setMessage(data.error || 'Application failed'); return; }
    setMessage(`Application submitted: ${data.loan.applicationNo}`);
    setTimeout(() => router.push('/member'), 1200);
  };
  const documentField = (key: 'propertyDocuments' | 'supportingDocuments' | 'documents') => <input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update(key, String(reader.result)); reader.readAsDataURL(file); }} className="rounded-xl border border-violet-200 bg-white px-3 py-2 text-sm" />;
  return <main className="min-h-screen bg-[#f8f5ff] px-4 py-10 text-[#1d1731] sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><Link href="/loans" className="font-bold text-[#6A11CB]">← Back to Loan Plans</Link><div className="mt-5 rounded-[2rem] bg-[#1d1234] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-200">Loan Application</p><h1 className="mt-2 text-3xl font-bold">Apply in six steps</h1><div className="mt-6 grid grid-cols-3 gap-2 md:grid-cols-6">{steps.map((label, index) => <button key={label} type="button" onClick={() => index <= step && setStep(index)} className={`rounded-xl p-2 text-left text-xs ${index === step ? 'bg-white text-[#4C1D95]' : 'bg-white/10 text-violet-100'}`}><b>{index + 1}</b><span className="mt-1 block">{label}</span></button>)}</div></div>{message && <p className="mt-5 rounded-xl bg-violet-100 px-4 py-3 text-sm font-semibold text-[#4C1D95]">{message}</p>}<section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm">
    {step === 0 && <div><h2 className="text-2xl font-bold">Member information</h2><p className="mt-2 text-slate-600">Your authenticated membership information will be attached automatically.</p></div>}
    {step === 1 && <div className="grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 text-2xl font-bold">Loan information</h2><label className="grid gap-2 text-sm font-semibold">Loan type<select value={form.type} onChange={(e) => update('type', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2"><option value="GENERAL">General Loan</option><option value="PROPERTY">Property Loan</option><option value="COMMODITY">Commodity Loan</option></select></label><label className="grid gap-2 text-sm font-semibold">Amount<input type="number" value={form.amount} onChange={(e) => update('amount', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" required /></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">Purpose<textarea value={form.purpose} onChange={(e) => update('purpose', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" required /></label>{form.type === 'PROPERTY' && <><label className="grid gap-2 text-sm font-semibold">Property type<input value={form.propertyType} onChange={(e) => update('propertyType', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" /></label><label className="grid gap-2 text-sm font-semibold">Property location<input value={form.propertyLocation} onChange={(e) => update('propertyLocation', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" /></label><label className="grid gap-2 text-sm font-semibold">Property value<input type="number" value={form.propertyValue} onChange={(e) => update('propertyValue', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" /></label></>}</div>}
    {step === 2 && <div className="grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 text-2xl font-bold">Financial information</h2><label className="grid gap-2 text-sm font-semibold">Repayment period (months)<input type="number" value={form.repaymentPeriod} onChange={(e) => update('repaymentPeriod', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" /></label><label className="grid gap-2 text-sm font-semibold">Repayment frequency<select value={form.repaymentFrequency} onChange={(e) => update('repaymentFrequency', e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2"><option>WEEKLY</option><option>MONTHLY</option><option>QUARTERLY</option></select></label><p className="md:col-span-2 rounded-xl bg-violet-50 p-4 text-sm text-slate-600">The system will calculate your processing fee, total repayment, and estimated installment from the selected loan product.</p></div>}
    {step === 3 && <div className="grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 text-2xl font-bold">Guarantor information</h2>{[['guarantorName','Full name'],['guarantorPhone','Phone'],['guarantorRelationship','Relationship'],['guarantorAddress','Address']].map(([key, label]) => <label key={key} className="grid gap-2 text-sm font-semibold">{label}<input value={form[key as keyof typeof form]} onChange={(e) => update(key, e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2" /></label>)}</div>}
    {step === 4 && <div className="grid gap-4"><h2 className="text-2xl font-bold">Document upload</h2><label className="grid gap-2 text-sm font-semibold">Identification document{documentField('documents')}</label>{form.type === 'PROPERTY' && <><label className="grid gap-2 text-sm font-semibold">Property documents{documentField('propertyDocuments')}</label><label className="grid gap-2 text-sm font-semibold">Supporting documents{documentField('supportingDocuments')}</label></>}</div>}
    {step === 5 && <div><h2 className="text-2xl font-bold">Review and submit</h2><dl className="mt-5 grid gap-3 rounded-2xl bg-violet-50 p-5 text-sm md:grid-cols-2"><div><dt className="text-slate-500">Loan type</dt><dd className="font-bold">{form.type}</dd></div><div><dt className="text-slate-500">Amount</dt><dd className="font-bold">₦{Number(form.amount || 0).toLocaleString()}</dd></div><div className="md:col-span-2"><dt className="text-slate-500">Purpose</dt><dd className="font-bold">{form.purpose}</dd></div></dl><button type="button" onClick={submit} className="mt-6 rounded-full bg-[#6A11CB] px-6 py-3 font-bold text-white">Submit Application</button></div>}
    {step < 5 && <div className="mt-8 flex justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((current) => current - 1)} className="rounded-full border border-violet-200 px-5 py-2 font-bold disabled:opacity-40">Previous</button><button type="button" onClick={() => setStep((current) => current + 1)} className="rounded-full bg-[#6A11CB] px-5 py-2 font-bold text-white">Continue</button></div>}
  </section></div></main>;
}

export default function LoanApplicationPage() {
  return <Suspense fallback={<main className="min-h-screen bg-[#f8f5ff] p-10 text-[#1d1731]">Loading application...</main>}><LoanApplicationForm /></Suspense>;
}
