'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type RequestRecord = { id: string; status: string; guarantorMembershipNo: string; requester?: { firstName: string; lastName: string; membership?: { membershipNo: string } }; guarantor?: { firstName: string; lastName: string; membership?: { membershipNo: string } }; loanApplication?: { applicationNo: string; type: string; amount: number; purpose: string } };

export default function GuarantorsPage() {
  const [received, setReceived] = useState<RequestRecord[]>([]);
  const [made, setMade] = useState<RequestRecord[]>([]);
  const [message, setMessage] = useState('');
  const load = () => fetch('/api/guarantor-requests').then((r) => r.json()).then((data) => { setReceived(data.received ?? []); setMade(data.made ?? []); }).catch(() => setMessage('Unable to load guarantor requests'));
  useEffect(() => { load(); }, []);
  const respond = async (id: string, status: string) => { const response = await fetch('/api/guarantor-requests', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); const data = await response.json(); setMessage(response.ok ? `Request ${status.toLowerCase()}.` : data.error || 'Unable to respond'); if (response.ok) load(); };
  return <main className="min-h-screen bg-[#f8f5ff] px-4 py-10 text-[#1d1731] sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Link href="/member" className="font-bold text-[#6A11CB]">← Back to dashboard</Link><div className="mt-5 rounded-[2rem] bg-gradient-to-r from-[#4C1D95] to-[#8b5cf6] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-200">Member Portal</p><h1 className="mt-2 text-3xl font-bold">Guarantor Requests</h1></div>{message && <p className="mt-5 rounded-xl bg-violet-100 px-4 py-3 text-sm font-semibold text-[#4C1D95]">{message}</p>}<section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Requests requiring your response</h2><div className="mt-5 space-y-4">{received.map((item) => <div key={item.id} className="rounded-2xl bg-violet-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.requester?.firstName} {item.requester?.lastName}</p><p className="text-sm text-slate-600">{item.loanApplication?.applicationNo} · {item.loanApplication?.type} · ₦{Number(item.loanApplication?.amount || 0).toLocaleString()}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold">{item.status === 'PENDING' ? 'Guarantor Request Pending' : item.status}</span></div>{item.status === 'PENDING' && <div className="mt-4 flex gap-2"><button type="button" onClick={() => respond(item.id, 'ACCEPTED')} className="rounded-full bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Accept</button><button type="button" onClick={() => respond(item.id, 'REJECTED')} className="rounded-full border border-rose-200 px-4 py-2 text-sm font-bold text-rose-600">Reject</button></div>}</div>)}{!received.length && <p className="text-sm text-slate-500">No guarantor requests are waiting for you.</p>}</div></section><section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Requests you made</h2><div className="mt-5 space-y-3">{made.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-violet-100 p-4"><span className="text-sm font-semibold">{item.guarantor?.firstName} {item.guarantor?.lastName} · {item.loanApplication?.applicationNo}</span><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-[#6A11CB]">{item.status === 'PENDING' ? 'Guarantor Request Pending' : item.status}</span></div>)}{!made.length && <p className="text-sm text-slate-500">No requests made yet.</p>}</div></section></div></main>;
}
