'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type Member = { id: string; firstName: string; lastName: string; email: string };
type Documents = { passportPhoto?: string | null; identificationDocument?: string | null; loans: Array<{ applicationNo: string; type: string; propertyDocuments?: string | null; supportingDocuments?: string | null; documents?: string | null }> };
export default function AdminDocumentsPage() {
  const [members, setMembers] = useState<Member[]>([]);
  const [selected, setSelected] = useState('');
  const [documents, setDocuments] = useState<Documents | null>(null);
  useEffect(() => { fetch('/api/members').then((r) => r.json()).then((data) => setMembers(data.members ?? [])); }, []);
  useEffect(() => { if (selected) fetch(`/api/documents?userId=${selected}`).then((r) => r.json()).then((data) => setDocuments(data.documents)); }, [selected]);
  const openDocument = (value: string | null | undefined) => { if (!value) return; const win = window.open(); if (win) { win.document.write(`<iframe src="${value}" style="width:100%;height:100%;border:0"></iframe>`); } };
  return <main className="min-h-screen bg-[#f8f5ff] px-4 py-10 text-[#1d1731] sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="font-bold text-[#6A11CB]">← Back to admin</Link><div className="mt-5 rounded-[2rem] bg-[#1d1234] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-200">Restricted Admin Area</p><h1 className="mt-2 text-3xl font-bold">Member Documents</h1><p className="mt-2 text-sm text-violet-100">Documents are retrieved only after staff authentication.</p></div><section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm"><label className="grid max-w-xl gap-2 text-sm font-bold">Select member<select value={selected} onChange={(e) => setSelected(e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2"><option value="">Choose a member</option>{members.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.email}</option>)}</select></label>{documents && <div className="mt-6 space-y-5"><div className="flex flex-wrap gap-3"><button type="button" onClick={() => openDocument(documents.passportPhoto)} disabled={!documents.passportPhoto} className="rounded-full bg-[#6A11CB] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Review passport</button><button type="button" onClick={() => openDocument(documents.identificationDocument)} disabled={!documents.identificationDocument} className="rounded-full border border-violet-200 px-4 py-2 text-sm font-bold text-[#6A11CB] disabled:opacity-40">Review identification</button></div>{documents.loans.map((loan) => <div key={loan.applicationNo} className="rounded-xl bg-violet-50 p-4"><p className="font-bold">{loan.applicationNo} · {loan.type}</p><div className="mt-3 flex flex-wrap gap-2">{[['documents','Application'],['propertyDocuments','Property'],['supportingDocuments','Supporting']].map(([key, label]) => <button key={key} type="button" onClick={() => openDocument(loan[key as keyof typeof loan] as string)} disabled={!loan[key as keyof typeof loan]} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-[#6A11CB] disabled:opacity-40">Review {label}</button>)}</div></div>)}</div>}</section></div></main>;
}
