'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type Documents = { passportPhoto?: string | null; identificationDocument?: string | null; loans: Array<{ applicationNo: string; type: string; propertyDocuments?: string | null; supportingDocuments?: string | null; documents?: string | null }> };
export default function DocumentsPage() {
  const [documents, setDocuments] = useState<Documents | null>(null);
  useEffect(() => { fetch('/api/documents').then((r) => r.json()).then((data) => setDocuments(data.documents)).catch(() => setDocuments(null)); }, []);
  const download = (data: string | null | undefined, name: string) => { if (!data) return; const link = document.createElement('a'); link.href = data; link.download = name; link.click(); };
  return <main className="min-h-screen bg-[#f8f5ff] px-4 py-10 text-[#1d1731] sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><Link href="/member" className="font-bold text-[#6A11CB]">← Back to dashboard</Link><div className="mt-5 rounded-[2rem] bg-gradient-to-r from-[#4C1D95] to-[#8b5cf6] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-200">Secure Member Area</p><h1 className="mt-2 text-3xl font-bold">My Documents</h1><p className="mt-2 text-sm text-violet-100">Documents are only returned after authentication and are not public URLs.</p></div><section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Personal documents</h2><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={() => download(documents?.passportPhoto, 'passport-photo')} disabled={!documents?.passportPhoto} className="rounded-full bg-[#6A11CB] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Download Passport</button><button type="button" onClick={() => download(documents?.identificationDocument, 'identification-document')} disabled={!documents?.identificationDocument} className="rounded-full border border-violet-200 px-4 py-2 text-sm font-bold text-[#6A11CB] disabled:opacity-40">Download ID</button></div></section><section className="mt-6 rounded-[2rem] border border-violet-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Loan documents</h2><div className="mt-4 space-y-3">{documents?.loans.map((loan) => <div key={loan.applicationNo} className="rounded-xl bg-violet-50 p-4"><p className="font-bold">{loan.applicationNo} · {loan.type}</p><div className="mt-3 flex flex-wrap gap-2">{[['documents','Application'],['propertyDocuments','Property'],['supportingDocuments','Supporting']].map(([key, label]) => <button key={key} type="button" onClick={() => download(loan[key as keyof typeof loan] as string, `${loan.applicationNo}-${label}`)} disabled={!loan[key as keyof typeof loan]} className="rounded-full bg-white px-3 py-1 text-xs font-bold text-[#6A11CB] disabled:opacity-40">{label} document</button>)}</div></div>)}{!documents?.loans.length && <p className="text-sm text-slate-500">No loan documents found.</p>}</div></section></div></main>;
}
